### ISSUE TITLE
Flows stats throws an exception when INT flows are retrieved from NoviFlow switches

### ISSUE THREAD

**Issue by jab1982** [kytos-ng/flow_stats#43]
Kytos-ng cloned and installed today. Python 3.9.2.

If I push the following payload via flow_manager:

```
{"flows": [{"cookie": 12282650349865594690, "cookie_mask": 0, "hard_timeout": 0, "idle_timeout": 0, "instructions": [{"actions": [{"action_type": "pop_int"}, {"action_type": "set_vlan", "vlan_id": 4001}, {"action_type": "output", "port": 16}], "instruction_type": "apply_actions"}], "match": {"dl_vlan": 4001, "in_port": 5}, "priority": 32768, "switch": "00:00:00:00:00:00:00:02", "table_id": 2}]}
```

The flow is successfully installed. Later, when the consistency routine runs and retrieves this flow, an exception is thrown:

```
kytos $> 2022-11-14 11:10:32,525 - ERROR [kytos.core.helpers] (thread_pool_sb_0) listen_to handler: <function Main.on_stats_received at 0x7fdb24186310>, args: (<Main(flow_stats, stopped 140578264000256)>, KytosEvent('kytos/of_core.flow_stats.received', {'switch': Switch('00:00:00:00:00:00:00:01'), 'replies_flows': [<napps.kytos.of_core.v0x04.flow.Flow object at 0x7fdaba1d4b80>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7fdac901ffa0>, <napps.kytos.of_core.v0x04.flow.Flow object at 0x7fdac901fc40>]}, 0)) traceback: Traceback (most recent call last):,   File "/root/dev/kytos/kytos/core/helpers.py", line 126, in handler_context,     result = handler(*args),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/amlight/flow_stats/main.py", line 151, in on_stats_received,     self.handle_stats_received(event),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/amlight/flow_stats/main.py", line 157, in handle_stats_received,     self.handle_stats_reply_received(replies_flows),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/amlight/flow_stats/main.py", line 161, in handle_stats_reply_received,     self.flows_stats_dict.update({flow.id: flow for flow in replies_flows}),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/amlight/flow_stats/main.py", line 161, in <dictcomp>,     self.flows_stats_dict.update({flow.id: flow for flow in replies_flows}),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/../napps/kytos/of_core/flow.py", line 99, in id,     flow_str = [self.as](http://self.as/)_json(sort_keys=True, include_id=False),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/../napps/kytos/of_core/flow.py", line 188, in as_json,     return json.dumps([self.as](http://self.as/)_dict(include_id), sort_keys=sort_keys),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 350, in as_dict,     flow_dict['instructions'] = [[instruction.as](http://instruction.as/)_dict() for,   File "/home/amlight/py39-kytos/var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 350, in <listcomp>,     flow_dict['instructions'] = [[instruction.as](http://instruction.as/)_dict() for,   File "/home/amlight/py39-kytos/var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 216, in as_dict,     instruction_dict['actions'] = [[action.as](http://action.as/)_dict(),   File "/home/amlight/py39-kytos/var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py", line 216, in <listcomp>,     instruction_dict['actions'] = [[action.as](http://action.as/)_dict(), AttributeError: 'NoneType' object has no attribute 'as_dict',
```

The code has the latest commit that addressed a similar issue:

```
commit a8abd039997ab089eb433ea170e254c17d0289b9 (HEAD -> master, origin/master, origin/HEAD)
Merge: 76c579f 3bf7088
Author: Vinicius Arcanjo <vindasil@fiu.edu>
Date:   Tue Nov 1 18:00:51 2022 -0300

    Merge pull request #19 from kytos-ng/fix/actions_as_dict

    [Fix] Action object has no attribute 'as_dict'
```

**Comment by jab1982** [comment]
The same error when retrieving the flows from  flow_manager

```
[3:55](https://amlight.slack.com/archives/CDPBW1E2H/p1668376548019549)
2022-11-13 16:55:08,944 - ERROR [kytos.core.controller] (Thread-569) Exception on /api/kytos/flow_manager/v2/flows [GET]
Traceback (most recent call last):
  File “/usr/local/lib/python3.9/dist-packages/flask/app.py”, line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File “/usr/local/lib/python3.9/dist-packages/flask/app.py”, line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File “/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py”, line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File “/usr/local/lib/python3.9/dist-packages/flask/app.py”, line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File “/usr/local/lib/python3.9/dist-packages/flask/app.py”, line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File “//var/lib/kytos/napps/kytos/flow_manager/main.py”, line 477, in list
    flows_dict = [cast_fields([flow.as](http://flow.as/)_dict()) for flow in switch.flows]
  File “//var/lib/kytos/napps/kytos/flow_manager/main.py”, line 477, in <listcomp>
    flows_dict = [cast_fields([flow.as](http://flow.as/)_dict()) for flow in switch.flows]
  File “//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py”, line 348, in as_dict
    flow_dict = super().as_dict(include_id=include_id)
  File “//var/lib/kytos/napps/../napps/kytos/of_core/flow.py”, line 149, in as_dict
    flow_dict[‘id’] = self.id
  File “//var/lib/kytos/napps/../napps/kytos/of_core/flow.py”, line 99, in id
    flow_str = [self.as](http://self.as/)_json(sort_keys=True, include_id=False)
  File “//var/lib/kytos/napps/../napps/kytos/of_core/flow.py”, line 188, in as_json
    return json.dumps([self.as](http://self.as/)_dict(include_id), sort_keys=sort_keys)
  File “//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py”, line 350, in as_dict
    flow_dict[‘instructions’] = [[instruction.as](http://instruction.as/)_dict() for
  File “//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py”, line 350, in <listcomp>
    flow_dict[‘instructions’] = [[instruction.as](http://instruction.as/)_dict() for
  File “//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py”, line 216, in as_dict
    instruction_dict[‘actions’] = [[action.as](http://action.as/)_dict()
  File “//var/lib/kytos/napps/../napps/kytos/of_core/v0x04/flow.py”, line 216, in <listcomp>
    instruction_dict[‘actions’] = [[action.as](http://action.as/)_dict()
AttributeError: ‘NoneType’ object has no attribute ‘as_dict’
```

**Comment by viniarck** [comment]
@jab1982 thanks for catching and reporting this. 

It turns out it was related to how an `ActionExperimenter` was being deserialized from `FlowStats` entries. These two PRs on `of_core` and `noviflow` fix the issue:

- https://github.com/kytos-ng/of_core/pull/88
- https://github.com/kytos-ng/noviflow/pull/21

Could you pull this branch `fix/exp_deser` from both `of_core` and `noviflow` and also double check?

I've tested out on Novi01 switch with the following action types `pop_int`, `push_int`, `send_report`, `add_int_metadata`:

```
kytos $> [flow.as_dict() for flow in controller.switches[sw1].flows]
Out[2]:
[{'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'dl_vlan': 3799, 'dl_type': 35020},
  'priority': 1000,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12321848580485677057,
  'id': '5cd66b3ec5c0437b3d163f18e8491250',
  'stats': {'byte_count': 810752,
   'duration_sec': 30,
   'duration_nsec': 334142320,
   'packet_count': 12668},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'port': 4294967293, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 11, 'dl_vlan': 3502, 'dl_type': 2048, 'nw_proto': 6},
  'priority': 200,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': 'cf1ee90816ed27552f94f1cff61404cb',
  'stats': {'byte_count': 0,
   'duration_sec': 3726,
   'duration_nsec': 678265656,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'push_int'}]},
   {'instruction_type': 'goto_table', 'table_id': 2}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 23, 'dl_src': '11:22:33:44:55:11'},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': '034029ff04cab792ba1d5aca5b6f1044',
  'stats': {'byte_count': 0,
   'duration_sec': 2389,
   'duration_nsec': 465959537,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'push_int'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 23, 'dl_src': '11:22:33:44:55:12'},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': 'f9e33adeade2ca5c9f5c756e1cca60ef',
  'stats': {'byte_count': 0,
   'duration_sec': 2389,
   'duration_nsec': 454982042,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'pop_int'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 23, 'dl_src': '11:22:33:44:55:13'},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': '26a336efb20df229166ddfea10cf52be',
  'stats': {'byte_count': 0,
   'duration_sec': 2389,
   'duration_nsec': 444993071,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'send_report'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 23, 'dl_src': '11:22:33:44:55:14'},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': '122144ee2c2976fe5cfb5c7faf72d561',
  'stats': {'byte_count': 0,
   'duration_sec': 2389,
   'duration_nsec': 430018186,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'add_int_metadata'}]}]}]

```
